<?php

namespace Efrogg\SynergyMaker;
use Symfony\Component\HttpKernel\Bundle\Bundle;

class SynergyMakerBundle extends Bundle
{
    protected function getContainerExtensionClass(): string
    {
        return parent::getContainerExtensionClass(); // TODO: Change the autogenerated stub
    }
}
